#!/usr/bin/env bash

set -eu -o pipefail

script_directory="$(cd -P "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
project_directory="${script_directory}/.."


version="${VERSION:-1.0.4}"
base_url='https://github.com/vantagedesign/ace-documentation/archive/refs/tags'
archive_file="${version}.tar.gz"

curl -sSLO "${base_url}/${archive_file}"

tar -xf "${archive_file}"

mv "ace-documentation-${version}" "${project_directory}/docs/themes/ace"

rm -rf "${archive_file}"
